runfile('C:/Users/yyw/.spyder-py3/scraw.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/scraw.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/scraw.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/imagecrawler/imagecrawler/spiders/pexels_scraper.py', wdir='C:/Users/yyw/imagecrawler/imagecrawler/spiders')
runfile('C:/Users/yyw/.spyder-py3/croll1.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/image.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/image.py', wdir='C:/Users/yyw/.spyder-py3')
debugfile('C:/Users/yyw/.spyder-py3/image.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/image.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/diff.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/image.py', wdir='C:/Users/yyw/.spyder-py3')
debugfile('C:/Users/yyw/.spyder-py3/image.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/image.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/image12.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/superresolution.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/img.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/sd.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/imge1.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/img12.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/img1213.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/image12.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/goodone1.py', wdir='C:/Users/yyw/.spyder-py3')
debugfile('C:/Users/yyw/.spyder-py3/goodone1.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/users/yyw/.spyder-py3/goodone1.py', wdir='C:/users/yyw/.spyder-py3')
debugfile('C:/users/yyw/.spyder-py3/goodone1.py', wdir='C:/users/yyw/.spyder-py3')
runfile('C:/users/yyw/.spyder-py3/goodone1.py', wdir='C:/users/yyw/.spyder-py3')
debugfile('C:/users/yyw/.spyder-py3/goodone1.py', wdir='C:/users/yyw/.spyder-py3')
runfile('C:/users/yyw/.spyder-py3/goodone1.py', wdir='C:/users/yyw/.spyder-py3')

## ---(Sun Aug 18 11:45:02 2019)---
runfile('C:/users/yyw/.spyder-py3/goodone1.py', wdir='C:/users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/crawlling.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/users/yyw/.spyder-py3/goodone1.py', wdir='C:/users/yyw/.spyder-py3')
runfile('C:/users/yyw/.spyder-py3/goodone1.py', wdir='C:/users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/goodone2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/Web Scraping with Python and Beautiful Soup.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/Web_Scraping_With_Excel_Using_Python.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/wikidatascraping.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/goodone2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/goodone2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/goodone2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/goodone2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/goodone2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/goodone2.py', wdir='C:/Users/yyw/.spyder-py3')
debugfile('C:/Users/yyw/.spyder-py3/goodone2.py', wdir='C:/Users/yyw/.spyder-py3')

## ---(Sun Aug 18 15:00:43 2019)---
runfile('C:/Users/yyw/.spyder-py3/goodone2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/goodone2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/goodone2.py', wdir='C:/Users/yyw/.spyder-py3')
debugfile('C:/Users/yyw/.spyder-py3/goodone2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/goodone2.py', wdir='C:/Users/yyw/.spyder-py3')

## ---(Sun Aug 18 15:41:50 2019)---
runfile('C:/Users/yyw/.spyder-py3/goodone2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/goodone3.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/goodone3.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/goodone3.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/goodone2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/pdftext.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/pdftext.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/translate.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/pdftext.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/pdftext.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/pdftext.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/pdftext.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/pdftext.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/pdftext.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/untitled2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/untitled2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/untitled2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/untitled2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/goodone2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/untitled2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/imgcrawl.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/untitled2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/untitled2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/untitled2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/imgcrawl.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/untitled2.py', wdir='C:/Users/yyw/.spyder-py3')

## ---(Mon Aug 19 00:14:54 2019)---
runfile('C:/Users/yyw/.spyder-py3/untitled2.py', wdir='C:/Users/yyw/.spyder-py3')

## ---(Mon Aug 19 11:10:19 2019)---
runfile('C:/Users/yyw/.spyder-py3/pdftext.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/untitled2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/imgcrawl.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/untitled2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/imgcrawl.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/untitled2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/mecro.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/untitled2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/pdftext.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/untitled2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/pdftext.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/untitled2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/pdftext.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/imgcrawl.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/untitled2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/pdftext.py', wdir='C:/Users/yyw/.spyder-py3')

## ---(Sat Aug 24 13:25:48 2019)---
runfile('C:/Users/yyw/.spyder-py3/untitled2.py', wdir='C:/Users/yyw/.spyder-py3')
runfile('C:/Users/yyw/.spyder-py3/pdftext.py', wdir='C:/Users/yyw/.spyder-py3')